packages:
  - 'packages/*'

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - vue-router
  - '@quasar/*'
  - '@fastify/middie@9.3.3'
  - '@types/node@26.1.0'
  - quasar@2.20.2
  - toml@4.1.2
  - vite@8.1.2
  - '@vitest/expect@4.1.10'
  - '@vitest/mocker@4.1.10'
  - '@vitest/pretty-format@4.1.10'
  - '@vitest/runner@4.1.10'
  - '@vitest/snapshot@4.1.10'
  - '@vitest/spy@4.1.10'
  - '@vitest/utils@4.1.10'
  - quasar@2.21.1
  - vitest@4.1.10
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true
overrides:
  unocss-preset-quasar-monorepo: 'link:'
