packages:
  - 'packages/*'

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - vue-router
  - '@quasar/*'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true
overrides:
  unocss-preset-quasar-monorepo: 'link:'
