/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QBtnDropdown: typeof import('quasar')['QBtnDropdown']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QCheckbox: typeof import('quasar')['QCheckbox']
    QChip: typeof import('quasar')['QChip']
    QDate: typeof import('quasar')['QDate']
    QDrawer: typeof import('quasar')['QDrawer']
    QHeader: typeof import('quasar')['QHeader']
    QIcon: typeof import('quasar')['QIcon']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QItemSection: typeof import('quasar')['QItemSection']
    QKnob: typeof import('quasar')['QKnob']
    QLayout: typeof import('quasar')['QLayout']
    QList: typeof import('quasar')['QList']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QPageSticky: typeof import('quasar')['QPageSticky']
    QRadio: typeof import('quasar')['QRadio']
    QSpace: typeof import('quasar')['QSpace']
    QToggle: typeof import('quasar')['QToggle']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
