// Cascade order: color utilities must be emitted AFTER component rules.
//
// `.q-btn` sets `background: transparent` (a shorthand, so it resets
// background-color). With utilities emitted first, a `bg-secondary q-btn` lost
// its fill and rendered transparent — the "Screenshot Review" button. Quasar
// and the reference deployment both place utilities last (reference: .q-btn at
// index 65, .bg-secondary at 100), so utilities win on equal specificity.
import { describe, it, expect } from 'vitest'
import { createGenerator } from 'unocss'
import { QuasarPreset, QuasarStyleEntries } from '../src/index.js'

async function cssFor(tokens: string): Promise<string> {
  const gen = await createGenerator({
    presets: [QuasarPreset({ styles: QuasarStyleEntries })]
  })
  const r = await gen.generate(tokens, { preflights: false })
  return r.css
}

/**
 * Index of the first rule carrying `sel`, whether it stands alone or is a member
 * of a comma-joined selector list. UnoCSS merges rules with identical declaration
 * bodies into one list, so a utility can share a block with a component rule;
 * matching only `sel{` would then miss it entirely.
 */
function indexOfBlock(css: string, sel: string): number {
  const m = new RegExp(`(?:^|[,\\n])\\s*(\\${sel})(?=\\s*[,{])`, 'm').exec(css)
  return m ? m.index + m[0].length - m[1].length : -1
}

describe('utility vs component cascade order', () => {
  it('emits bg-* utilities after the component rule they must override', async () => {
    const css = await cssFor('q-btn bg-secondary text-white')
    const bg = indexOfBlock(css, '.bg-secondary')
    const btn = indexOfBlock(css, '.q-btn')
    expect(bg).toBeGreaterThan(-1)
    expect(btn).toBeGreaterThan(-1)
    expect(bg).toBeGreaterThan(btn)
  })

  it('emits text-* utilities after component rules', async () => {
    const css = await cssFor('q-card text-primary')
    expect(indexOfBlock(css, '.text-primary')).toBeGreaterThan(
      indexOfBlock(css, '.q-card')
    )
  })

  it('still emits both the component rule and the utility', async () => {
    const css = await cssFor('q-btn bg-secondary')
    // The utility may lead a selector list rather than own a block of its own.
    expect(css).toMatch(
      /\.bg-secondary[^{}]*\{background-color:var\(--q-secondary\);\}/
    )
    expect(css).toContain('.q-btn{')
  })

  // The three assertions above only cover colours this preset generates itself.
  // Quasar's PALETTE colours (`bg-pink`, `bg-yellow-2`, …) are generated by the
  // engine from `extendTheme`, not by a rule here, so array order cannot place
  // them: they land wherever the engine puts them, which was BEFORE the
  // component rules. `.q-badge{background-color:var(--q-primary)}` then won on
  // equal specificity and every legend badge rendered primary. The explicit
  // layers put the component band ahead of `default`, so the engine's
  // utilities win too.
  it('emits engine-generated palette utilities after component rules', async () => {
    const css = await cssFor('q-badge bg-pink')
    const bg = indexOfBlock(css, '.bg-pink')
    const badge = indexOfBlock(css, '.q-badge')
    expect(bg).toBeGreaterThan(-1)
    expect(badge).toBeGreaterThan(-1)
    expect(bg).toBeGreaterThan(badge)
  })

  it('keeps the component band behind grid/container utilities', async () => {
    // The other half of the band order: `.column`/`.row` must stay ahead of the
    // components, or component layout stops winning on equal specificity (see
    // the note on `gridRules` in src/index.ts — `.q-item__section--main` grew to
    // 378px where the reference is 56px when this order was inverted).
    const css = await cssFor('column q-item')
    expect(indexOfBlock(css, '.column')).toBeLessThan(
      indexOfBlock(css, '.q-item')
    )
  })
})

describe('component modifier cascade', () => {
  it('keeps .q-rating__icon--active after the base rule it overrides', async () => {
    // UnoCSS's `mergeSelectors` groups selectors that share a declaration body
    // and parks the group at the alphabetically first of them. Nine components
    // yield `opacity:100%`, and `.q-carousel .q-carousel__thumbnail:hover` sorts
    // before `.q-rating__icon` — so the group carrying
    // `.q-rating__icon--active` landed ABOVE the base
    // `.q-rating__icon { opacity:40% }`. Equal specificity, earlier position:
    // the base won and every selected star rendered at 40%.
    //
    // `q-carousel` is in the token set on purpose: against `q-rating` alone
    // there is nothing to merge with, and the inversion cannot reproduce.
    const css = await cssFor('q-rating q-carousel')
    const base = indexOfBlock(css, '.q-rating__icon')
    const active = indexOfBlock(css, '.q-rating__icon--active')
    expect(base).toBeGreaterThan(-1)
    expect(active).toBeGreaterThan(base)
    expect(css).toMatch(/\.q-rating__icon\{[^}]*opacity:40%/)
    expect(css).toContain('.q-rating__icon--active{opacity:100%;}')
  })

  it('ships the no-dimming override at opacity 1', async () => {
    // The other side of the fold: `--no-dimming` still has to win over the
    // base `opacity:40%` — it does on specificity ((0,2,0) vs (0,1,0)),
    // whatever order the sheet picks.
    const css = await cssFor('q-rating')
    expect(css).toMatch(/\.q-rating--no-dimming \.q-rating__icon\{opacity:1;\}/)
  })
})

// The dark twin of a component rule is only safe when the BASE reads a token
// that does not flip (`var(--light-primary)` in the reference). Ours reads
// `var(--q-primary)`, which the dark token block redefines, so the twin was a
// no-op for an uncolored badge — and at (0,2,0) it outranked every `bg-*`
// utility (0,1,0), collapsing each status badge to primary in dark: all five
// dots of a status legend rendered #4cd9df in petboarding's dark sweep.
// The reference still carries the selector; the accepted divergence is recorded
// in fixtures/parity-baseline.json (date target 1, badge missing entry).
describe('dark component twins vs utilities', () => {
  it('emits no `.body--dark .q-badge` twin', async () => {
    const css = await cssFor('q-badge')
    expect(css).toContain('.q-badge{')
    expect(css).not.toMatch(/\.body--dark \.q-badge/)
  })

  it('leaves a coloured badge its colour in dark (utility is the only fill)', async () => {
    const css = await cssFor('q-badge bg-green')
    expect(css).toMatch(/\.bg-green[^{}]*\{[^}]*background-color/)
    // Nothing may re-assert a background on the badge under `.body--dark`.
    expect(css).not.toMatch(/\.body--dark[^{}]*q-badge[^{}]*\{/)
  })

  it('emits no `.body--dark .q-date__event` twin', async () => {
    const css = await cssFor('q-date')
    expect(css).not.toMatch(/\.body--dark \.q-date__event/)
  })
})
